### PR TITLE
add python 3.10 to test matrix

### PR DESCRIPTION
**Pull request by LilithWittmann**

### CODE REVIEW

**Comment by wirthual** [comment]
Onnxruntime is not yet available for 3.10. But it should change "end of this month"

https://github.com/microsoft/onnxruntime/issues/12133

**Comment by leqiao-1** [comment]
Tests on machine mac m1 with for inception_v2 model work fine from python 3.7 to python 3.10.

**Comment by wirthual** [comment]
Which version of onnxruntine do you have installed?

**Comment by leqiao-1** [comment]
> Tests on machine mac m1 with for inception_v2 model work fine from python 3.7 to python 3.10.

Sorry I mistake the issue.

**Comment by wirthual** [comment]
Onnx 1.12.0 is released, which supports python3.10

However it relies on a newer version of numpy that we currently have in our dependencies, and can not be installed because of this. Also the pandas dependency needs to be changed.

**Pull request closed without merging**
