### PR TITLE
Feat optionals

### PR DESCRIPTION
**Pull request by wirthual**
Draft for merging all optional packages into the Deutschland package.

This probably needs a bit of testing before it can be released. 

 - Should we make all subpackages optional? This is how it is now with deutschland[all] all packages will get installed
 - This might be a breaking change, since an update will  probably remove packages which were part of the package before (not tested yet)
 - How is the version resolving? Does it take super long everywhere? Or only with poetry and on my machine?
 - Can we make the package with tensorflow as dependency also optional and independent of the deutschland package? Thats a  huge dependency.

@LilithWittmann  let me know what you think :+1:

### CODE REVIEW

**Comment by LilithWittmann** [comment]
Looks generally good to me. I'm not sure about the update strategy. 
- Maybe for some time we make [all] the default option?
- Tensorflow issue should become obsolet with #55.

**Comment by severinsimmler** [comment]
> How is the version resolving? Does it take super long everywhere? Or only with poetry and on my machine?

It's considered best practice to just commit the `poetry.lock` by the way. With the `poetry.lock`, Poetry won't have to resolve all dependencies if you do a fresh install.

**Comment by wirthual** [comment]
I deleted the failing tests for now. Ready to merge from my side.

**Comment by LilithWittmann** [comment]
@wirthual should we try to merge this?

**Pull request merged**
